source 'https://rubygems.org'

gem 'rails', '5.0.1'
gem "activesupport", "5.0.1"
gem 'loofah', '2.0.3'
gem "i18n", "0.9.1"

gem 'sprockets-rails', '2.3.3'

gem 'tzinfo-data'


# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# Gems used only for assets and not required
# in production environments by default.
gem 'sass-rails', '~> 5.0', '>= 5.0.6'
gem 'coffee-rails', '4.2.1'
gem 'coffee-script'
gem 'coffee-script-source'
gem 'uglifier', '3.0.4'
gem 'therubyrhino'

gem 'less-rails-bootstrap'

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem "json", "1.8.6"
gem 'json-schema', '1.0.10'

gem "jruby-jars", "= 9.1.8.0"
gem 'atomic', '= 1.0.1'


group :test do
  gem 'rspec', "~> 3.6.0"
  gem 'rspec-rails'
  gem 'simplecov', "0.7.1"
end

group :development, :test do
  gem 'pry-debugger-jruby'
  gem 'pry-rails'
  gem 'pry-nav'
  gem 'rubocop', '~> 0.54.0', require: false
end

gem "mizuno", "0.6.11"

gem "net-http-persistent", "2.8"
gem "multipart-post", "1.2.0"
gem 'multi_json', '~> 1.13.1'

gem "rubyzip", "~> 1.2.1" # because of https://github.com/rubyzip/rubyzip/issues/315
gem "zip-zip", "0.3"

gem 'nokogiri', '1.8.1' # because of https://github.com/sparklemotion/nokogiri/issues/1673


require 'asutils'

# Allow plugins to provide their own Gemfiles too.
ASUtils.load_plugin_gems(self)
