source 'https://rubygems.org'

gem 'rails', '5.0.1'
gem "activesupport", "5.0.1"
gem 'sprockets-rails', '2.3.3'

gem 'tzinfo-data'


# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# Gems used only for assets and not required
# in production environments by default.
gem 'sass-rails'
gem 'coffee-rails'
gem 'coffee-script'
gem 'coffee-script-source'
gem 'uglifier'
gem 'therubyrhino'

gem 'less-rails'

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem "json", "1.8.6"
gem 'json-schema', '1.0.10'

gem 'useragent'

gem "jruby-jars", "= 9.1.8.0"
gem 'atomic', '= 1.0.1'


group :test do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'simplecov', "0.7.1"
end

gem "mizuno", "0.6.11"

gem "net-http-persistent", "2.8"
gem "multipart-post", "1.2.0"

gem "rubyzip", "1.0.0"
gem "zip-zip", "0.3"

gem "nokogiri", "1.7.0.1"


require 'asutils'

# Allow plugins to provide their own Gemfiles too.
ASUtils.load_plugin_gems(self)
