# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', '~> 6.1.6'

gem 'i18n'
gem 'loofah'
gem 'sprockets-rails'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Gems used only for assets and not required in production environments by default.
# Assets group was deprecated with Rails 4, but we still need it as we need to avoid using gems that include
# native extensions in production
group :assets do
  gem 'coffee-rails'
  gem 'coffee-script'
  gem 'coffee-script-source'
  gem 'sassc-rails'
  gem 'execjs'
end

gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'json'
gem 'json-schema', '~> 1.0.10'

gem 'atomic'
gem 'jruby-jars', '= 9.4.9.0'

group :test do
  gem 'rails-controller-testing'
  gem 'axe-core-rspec'
  gem 'dumb_delegator'
  gem 'rspec'
  # For performance testing
  gem 'rspec-benchmark'
  gem 'rspec-rails'
  gem 'simplecov'

  # selenium stuff
  gem 'factory_bot'
  gem 'factory_bot_rails'
  gem 'mechanize'
  gem 'parallel_tests'
  gem 'rspec-retry'
  gem 'selenium-webdriver'

  gem 'capybara'
  gem 'capybara-screenshot'
  # need access to ActiveSupport for helpers
  gem 'activesupport', '~> 6.1.6'
  # if the indexer requires it, our test suite requires it
  gem 'fog-aws', '~> 2.0.0', require: false

  gem 'rubyzip', '~> 2.4.1'
end

group :development, :test do
  gem 'pry-debugger-jruby', '>= 1.2.2'
  gem 'pry-nav'
  gem 'pry-rails'
  gem 'puma', '~> 6.4'
  gem 'rubyXL'
end

group :development do
  gem 'web-console'
end

gem 'multi_json'
gem 'multipart-post'
gem 'net-http-persistent', '>= 4.0.1'

gem 'nokogiri', '~> 1.13.10' # keep compatible with saxon-rb used in exports

require 'asutils'

# Allow plugins to provide their own Gemfiles too.
ASUtils.load_plugin_gems(self)

gem "zxcvbn-ruby", "~> 1.2"
