# docker-compose -f docker-compose-release.yml build
# docker-compose -f docker-compose-release.yml up

version: '3.8'
services:
  app:
    container_name: as_release_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
      - solr
    env_file:
      - .env.docker.release
  db:
    container_name: as_release_db
    image: mysql:8.0
    command: --character-set-server=UTF8MB4 --innodb_buffer_pool_size=2G --innodb_buffer_pool_instances=2 --log_bin_trust_function_creators=1
    ports:
      - "3308:3306"
    env_file:
      - .env.docker.db
  solr:
    container_name: as_release_solr
    build:
      context: ./solr
    image: archivesspace/solr:8.8
    command: solr-create -p 8983 -c archivesspace -d /archivesspace
    ports:
      - "8985:8983"
  web:
    container_name: as_release_proxy
    build:
      context: ./proxy
    image: archivesspace/proxy:1.13
    ports:
      - "80:80"
    depends_on:
      - app
