topics:
  # Accession Topics
  accession: '890044514/Managing+Accessions'
  accession_basic_information: '894107705/Creating+a+Minimal+Accession+Record'
  accession_extents: '470407276/Extents+Sub-Record'
  accession_dates: '4470407195/Dates+Sub-Record'
  accession_related_resources: '893976733/Related+Resources+Link'
  accession_linked_agents: '893911098/Agent+Links+-+Accessions'
  accession_subjects: '4482564100/Subject+Links+Sub-Record'
  accession_external_documents: '4468703237/External+Documents+Sub-Record'
  accession_rights_statements: '4469850127/Rights+Statements+Sub-Record+as+of+v2.1.0'
  accession_deaccessions: '4466245635/Deaccessions+Sub-Record'
  accession_instances: '894205992/Instances+Sub-Record+%28as+of+v1.5.0%29+-+Accessions'
  accession_collection_management: '4465000449/Collection+Management+Sub-Record'
  accession_metadata_rights_declarations: '4470800394/Metadata+Rights+Declarations+Sub-Record'
  accession_classifications: '4465000474/Classifications+Sub-Record'
  accession_user_defined: '4523229191/User-Defined+Fields+Sub-Record'
  # Resource Topics
  resource: '890142825/Managing+Resources'
  resource_basic_information: '893878578/Creating+and+Managing+Resource+Records'
  resource_dates: '4470407195/Dates+Sub-Record'
  resource_extents: '470407276/Extents+Sub-Record'
  resource_finding_aid: '894206166/Creating+a+Minimal+Resource+Record'
  resource_related_accessions: '893976733/Related+Resources+Link'
  resource_linked_agents: '896204929/Agent+Links+-+Resources'
  resource_subjects: '4482564100/Subject+Links+Sub-Record'
  resource_notes: '4523032582/Notes+Sub-Record'
  resource_external_documents: '4468703237/External+Documents+Sub-Record'
  resource_rights_statements: '4469850127/Rights+Statements+Sub-Record+as+of+v2.1.0'
  resource_metadata_rights_declarations: '4470800394/Metadata+Rights+Declarations+Sub-Record'
  resource_instances: '896204987/Instances+Sub-Record+as+of+v1.5.0+-+Resources'
  resource_deaccessions: '4466245635/Deaccessions+Sub-Record'
  resource_collection_management: '4465000449/Collection+Management+Sub-Record'
  resource_classifications: '4465000474/Classifications+Sub-Record'
  resource_load_via_spreadsheet: '1173913646/Import+Archival+Objects+from+Excel+or+CSV+File+from+v2.8.1)'
  resource_user_defined: '4523229191/User-Defined+Fields+Sub-Record'
  # Archival Objects
  archival_object: '894107902/Resource+Records+Components'
  archival_object_basic_information: '894206166/Creating+a+Minimal+Resource+Record'
  archival_object_dates: '4470407195/Dates+Sub-Record'
  archival_object_extents: '470407276/Extents+Sub-Record'
  archival_object_linked_agents: '896204929/Agent+Links+-+Resources'
  archival_object_subjects: '4482564100/Subject+Links+Sub-Record'
  archival_object_notes: '4523032582/Notes+Sub-Record'
  archival_object_external_documents: '4468703237/External+Documents+Sub-Record'
  archival_object_rights_statements: '4469850127/Rights+Statements+Sub-Record+as+of+v2.1.0'
  archival_object_instances: '896204987/Instances+Sub-Record+as+of+v1.5.0+-+Resources'
  # Digital Object Topics
  digital_object: '890142831/Managing+Digital+Objects'
  digital_object_basic_information: '894501241/Creating+Digital+Objects'
  digital_object_file_versions: '894435615/File+Versions'
  digital_object_dates: '4470407195/Dates+Sub-Record'
  digital_object_extents: '470407276/Extents+Sub-Record'
  digital_object_linked_agents: '896762114/Agent+Links+-+Digital+Objects'
  digital_object_subjects: '4482564100/Subject+Links+Sub-Record'
  digital_object_notes: '4523032582/Notes+Sub-Record'
  digital_object_classifications: '4465000474/Classifications+Sub-Record'
  digital_object_external_documents: '4468703237/External+Documents+Sub-Record'
  digital_object_rights_statements: '4469850127/Rights+Statements+Sub-Record+as+of+v2.1.0'
  digital_object_collection_management: '4465000449/Collection+Management+Sub-Record'
  digital_object_user_defined: '4523229191/User-Defined+Fields+Sub-Record'
  # Digital Object Components
  digital_object_component: '894566810/Digital+Object+Components'
  digital_object_component_basic_information: '894501241/Creating+Digital+Objects'
  digital_object_component_file_versions: '894435615/File+Versions'
  digital_object_component_dates: '4470407195/Dates+Sub-Record'
  digital_object_component_extents: '470407276/Extents+Sub-Record'
  digital_object_component_linked_agents: '896762114/Agent+Links+-+Digital+Objects'
  digital_object_metadata_rights_declarations: '4470800394/Metadata+Rights+Declarations+Sub-Record'
  digital_object_component_subjects: '4482564100/Subject+Links+Sub-Record'
  digital_object_component_notes: '4523032582/Notes+Sub-Record'
  digital_object_component_external_documents: '4468703237/External+Documents+Sub-Record'
  digital_object_component_rights_statements: '4469850127/Rights+Statements+Sub-Record+as+of+v2.1.0'
  # Subjects
  subject: '890339535/Managing+Subjects'
  subject_basic_information: '894566641/Creating+New+Subject+Records'
  subject_terms: 894664812/Subject+Record+Fields
  subject_external_documents: '4468703237/External+Documents+Sub-Record'
  # Agent Persons
  agent_person: '890011751/Managing+Agents'
  agent_person_dates_of_existence: '1942945864/Agent+Record+Fields+from+3.0'
  agent_person_names: '1942945864/Agent+Record+Fields+from+3.0'
  agent_person_contact_details: '1942945864/Agent+Record+Fields+from+3.0'
  agent_person_notes: '1942945864/Agent+Record+Fields+from+3.0'

  # Agent Family
  agent_family: '890011751/Managing+Agents'
  agent_family_dates_of_existence: '1942945864/Agent+Record+Fields+from+3.0'
  agent_family_names: '1942945864/Agent+Record+Fields+from+3.0'
  agent_family_contact_details: '1942945864/Agent+Record+Fields+from+3.0'
  agent_family_notes: '1942945864/Agent+Record+Fields+from+3.0'
  # Agent Corporate Entity
  agent_corporate_entity: '890011751/Managing+Agents'
  agent_corporate_entity_dates_of_existence: '1942945864/Agent+Record+Fields+from+3.0'
  agent_corporate_entity_names: '1942945864/Agent+Record+Fields+from+3.0'
  agent_corporate_entity_contact_details: '1942945864/Agent+Record+Fields+from+3.0'
  agent_corporate_entity_notes: '1942945864/Agent+Record+Fields+from+3.0'
  # Agent Software
  agent_software: '890011751/Managing+Agents'
  agent_software_dates_of_existence: '1942945864/Agent+Record+Fields+from+3.0'
  agent_software_names: '1942945864/Agent+Record+Fields+from+3.0'
  agent_software_contact_details: '1942945864/Agent+Record+Fields+from+3.0'
  agent_software_notes: '1942945864/Agent+Record+Fields+from+3.0'
  # Agent Shared
  agent_sources: '1942945864/Agent+Record+Fields+from+3.0'
  agent_record_identifiers: '1942945864/Agent+Record+Fields+from+3.0'
  agent_maintenance_histories: '1942945864/Agent+Record+Fields+from+3.0'
  agent_other_agency_codes: '1942945864/Agent+Record+Fields+from+3.0'
  agent_conventions_declarations: '1942945864/Agent+Record+Fields+from+3.0'
  agent_identifiers: '1942945864/Agent+Record+Fields+from+3.0'
  agent_alternate_sets: '1942945864/Agent+Record+Fields+from+3.0'
  agent_record_controls: '1942945864/Agent+Record+Fields+from+3.0'
  agent_genders: '1942945864/Agent+Record+Fields+from+3.0'
  agent_place: '1942945864/Agent+Record+Fields+from+3.0'
  agent_occupation: '1942945864/Agent+Record+Fields+from+3.0'
  agent_function: '1942945864/Agent+Record+Fields+from+3.0'
  agent_topic: '1942945864/Agent+Record+Fields+from+3.0'
  agent_used_language: '1942945864/Agent+Record+Fields+from+3.0'
  agent_external_documents: '4468703237/External+Documents+Sub-Record'
  agent_external_resources: '1976631381/Relation+Information+-+Linking+Agent+Record+s+and+Related+External+Resources+to+an+Agent+Record+v.3.0.0'
  agent_related_agents: '1976631381/Relation+Information+-+Linking+Agent+Record+s+and+Related+External+Resources+to+an+Agent+Record+v.3.0.0'
  agent_required: '2209677336/Editing+Required+Fields+in+Agent+Records'
  agent_merge: '1961197569/Merging+Agent+Records+from+v3.0'

  # Location
  location: '889946202/Managing+Locations'
  # Event
  event: '890011766/Events'
  event_basic_information: '894697657/Events+Basic+Information'
  event_date: '894501206/Events+Date'
  event_linked_agents: '894533814/Events+Agent+Links'
  event_linked_records: '894566764/Events+Record+Links'
  # Classification
  classification: '890208308/Managing+Classifications'
  # Classification Term
  classification_term: '894664901/Defining+a+Classification+Hierarchy'
  # Import
  import: '894566467/Importing+Records+Overview'
  # Search
  search: '892174361/About+Searching+and+Sorting+Results'
  # Manage Groups
  repository_groups: '893583404/Managing+User+Permission+Groups'
  # Managing User Access
  repository_users: '890011725/Managing+User+Accounts+and+User+Permissions'
  # Repositories
  repository: '890339516/Managing+Repositories'
  # Manage Users
  user: '890011725/Managing+User+Accounts+and+User+Permissions'
  # Controlled Value Lists
  enumeration: '890208293/Managing+Controlled+Value+Lists'
  # Assessments
  assessment: '894435657/Managing+Assessments'

  # Preferences
  preference: '892239901/Setting+Preferences+as+of+v2.8.1'

  # Bulk Import Templates
  bulk_import_templates: '894566467/Importing+Records+Overview'

  # Bulk Archival Object Updater job
  bulk_archival_object_updater_job: '4158423042/Bulk+Update+of+Archival+Objects+as+of+v4.0'

  # Custom Reports
  custom_report_templates: '2914877469/Creating+Managing+and+Running+Custom+Reports'
