# frozen_string_literal: true

source 'https://rubygems.org'

gem 'atomic', '= 1.0.1'
gem 'bcrypt', '3.1.7'
gem 'childprocess', '~> 3.0', '< 4.0'
gem 'jdbc-derby', '10.12.1.1'
gem 'jdbc-mysql', '>=8.0', group: :development
gem 'jruby-jars', '= 9.2.20.1'
gem 'json'
gem 'json-schema', '1.0.10'
gem 'net-ldap', '~> 0.16.0'
gem 'nokogiri', '>= 1.10.8'
gem 'rufus-lru', '1.0.5'
gem 'rufus-scheduler', '~> 2.0.24'
gem 'rubyXL', '~> 3.4', '>= 3.4.9'
gem 'saxerator', '= 0.9.2'
gem 'saxon-rb', '~> 0.8.3'
gem 'sequel', '~> 5.9.0'
gem 'sinatra', '~> 2.2', require: false
gem 'sinatra-contrib', '~> 2.2', require: false
gem 'tzinfo'

gem 'warbler', '2.0.5', group: :build

gem 'activesupport', '< 6.0'
gem 'i18n', '< 1.0'
gem 'oai', '0.4.0'

gem 'rrtf'

group :test do
  gem 'factory_bot'
  gem 'rack-test'
  gem 'rspec'
  gem 'rspec-core'
  gem 'simplecov'
end

group :development, :test do
  gem 'pry'
  gem 'pry-debugger-jruby'
  gem 'pry-nav'
  gem 'mizuno-aspace'
end

gem 'multipart-post', '1.2.0'
gem 'net-http-persistent', '>= 4.0.1'
gem 'rjack-jackson', '1.8.11.0'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Allow plugins to provide their own Gemfiles too.
require 'asutils'
ASUtils.load_plugin_gems(self)

gem "actionmailer", "~> 5.2"
