source "http://rubygems.org"

gem "atomic", '= 1.0.1'
gem "sinatra", :require => false
gem "sinatra-reloader", :require => false
gem "sequel"
gem "rack-session-sequel"
gem "jdbc-mysql"
gem "jdbc-derby"
gem "json"
gem "bcrypt-ruby"
gem "rspec"
gem "json-schema"
gem "simplecov"
gem "jruby-jars", "= 1.7.3"
gem "warbler"
gem "nokogiri"
gem "factory_girl"
gem "rufus-scheduler"
gem "net-ldap"

gem "axlsx"
gem "flying_saucer"

group :test do
  gem "ladle"
end
