report_type: jdbc
uri_suffix: accessions_uncataloged
description: "Displays only those accession(s) that have not been checked as cataloged. Report contains accession number, linked resources, title, extent, cataloged, date processed, a count of the number of records selected that are not checked as cataloged, and the total extent number for those records not cataloged."
