source 'https://rubygems.org'

# Middleman
gem 'middleman', '~>3.3.10'
gem 'middleman-gh-pages', '~> 0.0.3'
gem 'middleman-syntax', '~> 2.0.0'
gem 'middleman-autoprefixer', '~> 2.4.4'
gem 'sprockets', '~> 2.12.5'
gem 'rouge', '~> 1.9.0'
gem 'redcarpet', '~> 3.3.1'

gem 'rake', '~> 12.3.3'
gem 'therubyracer', '~> 0.12.1', platforms: :ruby

# In order to remove deprecation warning with the solution of
# You can use the sass-convert command to automatically fix most cases.
git 'https://github.com/ably-forks/compass', branch: 'sass-deprecation-warning-fix' do
  gem 'compass-core'
end
