source 'https://rubygems.org'

# Middleman
gem 'middleman', '~> 4.3', '>= 4.3.5'
gem 'middleman-gh-pages', '~> 0.4.1'
gem 'middleman-syntax', '~> 3.2'
gem 'middleman-autoprefixer', '~> 2.10', '>= 2.10.1'
gem 'sprockets'
gem 'rouge'
gem 'redcarpet'

gem 'rake'
gem 'therubyracer', platforms: :ruby

# In order to remove deprecation warning with the solution of
# You can use the sass-convert command to automatically fix most cases.
git 'https://github.com/ably-forks/compass', branch: 'sass-deprecation-warning-fix' do
  gem 'compass-core'
end
