source 'https://rubygems.org'


gem 'atomic'

gem 'json-schema'
gem "net-http-persistent", "2.8"
gem "multipart-post", "1.2.0"

gem 'puma'



# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'

gem 'rails-api' 

group :assets do
  gem 'sass-rails', '~> 5.0'

  gem 'uglifier', '>= 1.3.0'

  gem 'compass-rails'
  gem 'zurb-foundation'
end

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development


# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
