report_type: jdbc
uri_suffix: accessions_receipt
description: "Displays a receipt indicating accessioning of materials. Report contains accession number, title, extent, accession date, and repository."
