  BASE_SEARCH_PARAMS =
      [["q", String, "A search query string",
        :optional => true],
       ["aq", JSONModel(:advanced_query), "A json string containing the advanced query",
        :optional => true],
       ["type",
        [String],
        "The record type to search (defaults to all types if not specified)",
        :optional => true],
       ["sort",
        String,
        "The attribute to sort and the direction e.g. &sort=title desc&...",
        :optional => true],
       ["facet",
        [String],
        "The list of the fields to produce facets for",
        :optional => true],
       ["filter_term", [String], "A json string containing the term/value pairs to be applied as filters.  Of the form: {\"fieldname\": \"fieldvalue\"}.",
        :optional => true],
       ["simple_filter", [String], "A simple direct filter to be applied as a filter. Of the form 'primary_type:accession OR primary_type:agent_person'.",
        :optional => true],
        ["exclude",
        [String],
        "A list of document IDs that should be excluded from results",
        :optional => true],
       ["root_record",
        String,
        "Search within a collection of records (defined by the record at the root of the tree)",
        :optional => true]]

