# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport', '5.2.5'
gem 'atomic', '= 1.0.1'
gem 'excon', '>= 0.76.0'
gem 'fog-aws', '2.0.0', require: false
gem 'i18n', '0.9.1'
gem 'json', '2.3.0'
gem 'mime-types'
gem 'multi_json', '~> 1.15.0'
gem 'nokogiri', '>= 1.10.8'
gem 'rack-test', '~> 1.1.0'
gem 'sinatra', '2.0.5', require: false
gem 'sinatra-contrib', '2.0.5', require: false
