# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport', '~> 6.1.6'
gem 'atomic'
gem 'excon', '>= 0.76.0'
gem 'fog-aws', '~> 2.0.0', require: false
gem 'i18n'
gem 'json'
gem 'mime-types'
gem 'multi_json'
gem 'nokogiri'
gem 'sinatra', '~> 3.2', require: false
gem 'sinatra-contrib', '~> 3.2', require: false
gem 'multipart-post', '~> 2.4'
gem 'net-http-persistent', '>= 4.0.1'
gem 'json-schema', '~> 1.0.10'

group :development, :test do
  gem 'pry'
  gem 'pry-debugger-jruby'
  gem 'pry-nav'
end

group :test do
  gem 'factory_bot'
  gem 'rack-test'
  gem 'rspec'
  gem 'rspec-core'
  gem 'simplecov'
  gem 'vcr'
  gem 'webmock'
end
