# frozen_string_literal: true

require 'asutils'
ASUtils.load_common_gems(self)
common_rails_gems

# For handling HTML enities when processing exports as XML
gem 'htmlentities'

# use bootstrap's sass
gem 'bootstrap-sass'
# Use SCSS for stylesheets

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '3.0.4'
# Use font-awesome icons
gem 'font-awesome-sass'

# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '4.2.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyrhino'
# Use jquery as the JavaScript library
gem 'jquery-rails'

gem 'excon', '>= 0.76.0'


# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'

gem 'listen'

# Allow plugins to provide their own Gemfiles too.
ASUtils.load_plugin_gems(self)
