source 'https://rubygems.org'

gem 'rails', '3.2.22.2'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'coffee-script', '= 2.3.0'
  gem 'coffee-script-source', '= 1.8.0'

  gem 'uglifier', '>= 1.0.3'
  gem 'therubyrhino'
  gem 'less-rails', '~> 2.6.0'

end

gem 'jquery-rails', '~> 3.1.0'
gem "json", "1.8.3"
gem 'json-schema', '1.0.10'
gem "jruby-jars", "= 9.1.6.0"

gem 'atomic', '= 1.0.1'
gem "puma", "2.8.2"



gem "net-http-persistent", "2.8"
gem "multipart-post", "1.2.0"

group :development, :test do
  gem 'rspec', '~> 3.3.0'
  gem 'rspec-rails'
  gem 'factory_girl', "~> 4.1.0"
end


# Allow plugins to provide their own Gemfiles too.
#
require 'asutils'
ASUtils.load_plugin_gems(self)
