source 'https://rubygems.org'

gem 'rails', '3.2.13'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyrhino'

  gem 'uglifier', '>= 1.0.3'

  gem 'less-rails'
end

gem 'jquery-rails'

gem 'json-schema', '1.0.10'

gem "jruby-jars", "= 1.7.3"

gem 'atomic'
