# The contents of the hash declared below will be loaded into the global preferences
# record at system start-up. This has the effect of setting defaults for user preferences.
# Only keys matching propoerties declared in common/schemas/defaults.rb will be loaded.
# TAKE CARE editing this file as errors will prevent the system from starting.
{
  'show_suppressed' => false,
  'publish' => false,
  'accession_browse_column_1' => 'title',
  'accession_browse_column_2' => 'identifier',
  'accession_browse_column_3' => 'accession_date',
  'accession_browse_column_4' => 'audit_info',
  'accession_browse_column_5' => '',
  'resource_browse_column_1' => 'title',
  'resource_browse_column_2' => 'identifier',
  'resource_browse_column_3' => 'resource_type',
  'resource_browse_column_4' => 'level',
  'resource_browse_column_5' => 'audit_info',
  'archival_object_browse_column_1' => 'title',
  'archival_object_browse_column_2' => 'level',
  'archival_object_browse_column_3' => 'context',
  'archival_object_browse_column_4' => 'audit_info',
  'archival_object_browse_column_5' => '',
  'digital_object_browse_column_1' => 'title',
  'digital_object_browse_column_2' => 'digital_object_type',
  'digital_object_browse_column_3' => 'restrictions',
  'digital_object_browse_column_4' => 'audit_info',
  'digital_object_browse_column_5' => '',
  'digital_object_component_browse_column_1' => 'title',
  'digital_object_component_browse_column_2' => 'context',
  'digital_object_component_browse_column_3' => 'audit_info',
  'digital_object_component_browse_column_4' => '',
  'digital_object_component_browse_column_5' => '',
  'subjects_browse_column_1' => 'title',
  'subjects_browse_column_2' => 'audit_info',
  'subjects_browse_column_3' => '',
  'subjects_browse_column_4' => '',
  'subjects_browse_column_5' => '',
  'assessment_browse_column_1' => 'assessment_id',
  'assessment_browse_column_2' => 'assessment_records',
  'assessment_browse_column_3' => 'assessment_surveyors',
  'assessment_browse_column_4' => 'assessment_completed',
  'assessment_browse_column_5' => 'audit_info',
  'agent_browse_column_1' => 'primary_type',
  'agent_browse_column_2' => 'title',
  'agent_browse_column_3' => 'source',
  'agent_browse_column_4' => 'audit_info',
  'agent_browse_column_5' => '',
  'multi_browse_column_1' => 'primary_type',
  'multi_browse_column_2' => 'title',
  'multi_browse_column_3' => 'context',
  'multi_browse_column_4' => 'identifier',
  'multi_browse_column_5' => 'audit_info'
}
