source "http://rubygems.org"

gem 'nokogiri', '>=1.8.2' # because of https://github.com/sparklemotion/nokogiri/issues/1714
gem "factory_bot"
gem "rufus-lru"
gem "net-http-persistent"
gem "multipart-post"

group :development do
  gem 'mocha'
end
