source "http://rubygems.org"

gem 'nokogiri', '1.8.5'
gem 'factory_bot', '~> 4.11', '>= 4.11.1'
gem "rufus-lru"
gem "net-http-persistent"
gem "multipart-post"

group :development do
  gem 'mocha'
end
