# A sample Gemfile
source "http://rubygems.org"


group "test" do
	gem "selenium-webdriver", "2.41.0"
	gem "rspec", "2.12.0"
 	gem "rspec-core", "2.12.1"
end


gem 'multi_json', '1.10.0'
gem "rubyzip", "1.0.0"
gem "zip-zip", "0.3"
