# A sample Gemfile
source "http://rubygems.org"


group "test" do
	gem "selenium-webdriver", "2.45.0"
	gem "rspec", "~> 3.3.0"
end


gem 'multi_json', '1.10.0'
gem "rubyzip", "1.0.0"
gem "zip-zip", "0.3"
