report_type: jdbc
uri_suffix: accessions_production
description: "Displays accessions that have been accessioned, processed, and cataloged during a specified time period. Produces a summary statement of the total number of accessions, the total extent, total extent processed, and extent cataloged within the specified date range."
