#!/bin/bash

set -eu
echo "Adding upstream" # [for forks] redundant, but harmless, if cloning archivesspace directly
git remote -v | grep -w upstream || git remote add upstream https://github.com/archivesspace/archivesspace.git
git remote set-url upstream https://github.com/archivesspace/archivesspace.git

echo "Copying config files"
cp .devcontainer/aliases ~/.bash_aliases

echo "Resetting gems folder permissions"
sudo chown vscode build/gems

echo "Starting MySQL (MariaDB) and Solr"
sudo service mariadb start
sudo service solr start

echo "Creating dev & test Solr cores"
sudo su - solr -c "/opt/solr/bin/solr create -p 8983 -c asdev -d /workspaces/archivesspace/solr"
sudo su - solr -c "/opt/solr/bin/solr create -p 8983 -c astest -d /workspaces/archivesspace/solr"

echo "Downloading MySQL connector"
wget https://repo1.maven.org/maven2/mysql/mysql-connector-java/$MYSQL_CONNECTOR_VERSION/mysql-connector-java-$MYSQL_CONNECTOR_VERSION.jar && mv mysql-connector-java-$MYSQL_CONNECTOR_VERSION.jar ./common/lib/

echo "Creating dev & test DB"
sudo mysql -u root <<SQL
CREATE USER IF NOT EXISTS 'as'@'localhost' IDENTIFIED BY 'as123';
CREATE DATABASE IF NOT EXISTS asdev  DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS astest DEFAULT CHARACTER SET utf8mb4;
GRANT ALL PRIVILEGES ON asdev.* to 'as'@'localhost';
GRANT ALL PRIVILEGES ON astest.* to 'as'@'localhost';
SQL

gzip -dc build/mysql_db_fixtures/accessibility.sql.gz | sudo mysql -u root asdev

echo "Running bootstrap"
./build/run bootstrap

echo "Clearing local indexer state"
./build/run solr:reset

echo "Running database migrations"
./build/run db:migrate

echo "Installing development tools"
sudo gem install --no-document debug rubocop solargraph
