report_type: jdbc
uri_suffix: resources_restrictions_list
description: "Displays only those resource(s) that are restricted. Report contains title, resource identifier, level, date range, creator names, and a total extent number of the records selected that are checked as restrictions apply."
