# frozen_string_literal: true

source 'https://rubygems.org'

gem 'byebug'
gem 'capybara'
gem 'capybara-screenshot'
gem 'cucumber'
gem 'cucumber-cucumber-expressions', '~> 18.0' # TODO: remove this line once:  cucumber/cucumber-ruby#1820 is resolved
gem 'cuke_linter'
gem 'pdf-reader'
gem 'rake'
gem 'rspec-expectations'
gem 'rubocop', '~> 1.82.0', require: false
gem 'selenium-webdriver'
