report_type: jdbc
uri_suffix: accessions_deaccessions_list
description: "Displays a list of accession record(s) and linked deaccession record(s). Report contains accession number, title, extent, accession date, container summary, cataloged, date processed, rights transferred, linked deaccessions and total extent of all deaccessions."
