report_type: jdbc
uri_suffix: names_list_all
description: "Displays names and all resource(s), digital object(s) and accession(s) to which the name is linked. Report contains sort name, name type, name source and any resources, digital object or accession records linked to that name."
