#!/bin/bash

cd `dirname $0`

version=$1

case $version in
"")
  git_version=`git rev-parse --abbrev-ref HEAD 2>/dev/null`-`git rev-parse --short HEAD 2>/dev/null`
  echo Please specify a version name for the build.
  echo
  echo Usage: build_release [ -g \| -t \| version ]
  echo "   " -g "     " name the version using the current git ref \[$git_version\]
  echo "   " -t "     " name the version using a timestamp
  echo "   " version "" specify a version name explicitly
  echo
  echo The release will be packaged as archivesspace.zip in the archivesspace root
  ;;
"-g")
  git_version=`git rev-parse --abbrev-ref HEAD 2>/dev/null`-`git rev-parse --short HEAD 2>/dev/null`
  echo Building release with version: $git_version
  ../build/run build-dist -Dversion="$git_version"
  ;;
"-t")
  echo Building release with a timestamp version
  ../build/run build-dist
  ;;
*)
  echo Building release with version: $version
  ../build/run build-dist -Dversion="$version"
  ;;
esac
