#!/bin/bash
#
# Run IRB with our environment set up.
#
# Non-portable!  Just for development purposes...

conf=""

export BUNDLE_GEMFILE="`dirname $0`/../backend/Gemfile"
JAVA_OPTS="$JAVA_OPTS -Daspace.config.search_user_secret=devserver -Daspace.config.public_user_secret=devserver -Daspace.config.staff_user_secret=devserver"
export JAVA_OPTS
"`dirname $0`/jruby" -I. -Icommon -e "require 'backend/app/main'; require 'irb'; $conf; IRB.start" ${1+"$@"}
