#!/bin/bash
#
# Run IRB with our environment set up.
#
# Non-portable!  Just for development purposes...

which rlwrap &>/dev/null

if [ "$?" = "0" ]; then
    rlwrap="rlwrap"
else
    rlwrap=""
fi


JAVA_OPTS="$JAVA_OPTS -Daspace.config.search_user_secret=devserver"
export JAVA_OPTS
$rlwrap "`dirname $0`/jruby" -I. -e "require 'backend/app/main'; require 'irb'; IRB.start" ${1+"$@"}
