#!/bin/bash
#
# Run IRB with our environment set up.
#
# Non-portable!  Just for development purposes...

which rlwrap &>/dev/null

if [ "$?" = "0" ]; then
    rlwrap="rlwrap"
else
    rlwrap=""
fi


$rlwrap "`dirname $0`/jruby" -e "require 'irb'; IRB.start" ${1+"$@"}
