source "https://rubygems.org"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :test do
  gem "json", "1.8.0"
  gem 'multi_json', '~> 1.12.1'
  gem 'rubyzip', '1.0.0'
  gem "sinatra", "1.4.7", :require => false
  gem "activesupport", "5.0.1"
  gem "selenium-webdriver", "= 3.3.0"
  gem "rspec"
  gem "rspec-retry"
  gem "parallel_tests", "~> 2.14.0"
  gem "factory_girl"
  gem "json-schema", "1.0.10"
  gem "atomic", '= 1.0.1'
  gem "net-http-persistent", "2.8"
  gem "multipart-post", "1.2.0"

  gem "pry"
end

group :development do

  gemfile_local = File.join(File.dirname(__FILE__), 'Gemfile.local')
  if File.readable?(gemfile_local)
    puts "Loading #{gemfile_local}..." if $DEBUG
    instance_eval(File.read(gemfile_local))
  end
end


