# frozen_string_literal: true

source 'https://rubygems.org'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'i18n', '0.9.1'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'nokogiri', '1.8.5'

group :test do
  gem 'activesupport', '5.0.7.2'
  gem 'atomic', '~> 1.1', '>= 1.1.101'
  gem 'factory_bot', '~> 5.0', '>= 5.0.2'
  gem 'json', '2.2.0'
  gem 'json-schema', '1.0.10'
  gem 'multi_json', '~> 1.13.1'
  gem 'multipart-post', '1.2.0'
  gem 'net-http-persistent', '3.0.1'
  gem 'parallel_tests', '~> 2.29', '>= 2.29.1'
  gem 'rspec', '~> 3.8'
  gem 'rspec-retry'
  gem 'rubyzip', '~> 1.2.2'
  gem 'selenium-webdriver', '~> 3.142', '>= 3.142.3'
  gem 'sinatra', '1.4.7', require: false

  gem 'mechanize'
  gem 'mime-types', '~> 3.2', '>= 3.2.2'
  gem 'pry'
  gem 'pry-debugger-jruby'
  gem 'pry-nav'
end

group :development, :test do
  gem 'rubocop', '~> 0.72.0', require: false
end

group :development do
  gemfile_local = File.join(File.dirname(__FILE__), 'Gemfile.local')
  if File.readable?(gemfile_local)
    puts "Loading #{gemfile_local}..." if $DEBUG
    instance_eval(File.read(gemfile_local))
  end
end
