name: Trigger all specs

on:
  workflow_dispatch:
    inputs:
      java-version:
        description: Java version to run specs on
        required: true
        type: choice
        options:
          - '11'
          - '17'
        default: '11'
      browser:
        description: Which browser to use
        required: true
        type: choice
        options:
          - 'chrome'
          - 'firefox'
        default: 'firefox'

jobs:
  codescan:
    uses: ./.github/workflows/codescan.yml
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version || 11 }} # https://archivesspace.atlassian.net/browse/ANW-2022

  frontend:
    uses: ./.github/workflows/frontend.yml
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version || 11 }}
      group-choice: 'all'
      browser: ${{ inputs.browser || 'chrome' }}

  backend:
    uses: ./.github/workflows/backend.yml
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version || 11 }}

  accessibility:
    uses: ./.github/workflows/accessibility.yml
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version || 11 }}
      browser: ${{ inputs.browser || 'chrome' }}

  indexer:
    uses: ./.github/workflows/indexer.yml
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version || 11 }}

  public:
    uses: ./.github/workflows/public.yml
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version || 11 }}
      browser: ${{ inputs.browser || 'chrome' }}
