name: Frontend Testing

on:
  pull_request:
    paths:
      - '.github/workflows/frontend.*'
      - 'frontend/**'
      - 'common/**'
      - 'solr/**'

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ec2-instance-type: t3.nano
          subnet-id: subnet-0176f7d2f09ef0116
          security-group-id: sg-0e9991f439771a820

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # required to get output from the start-runner job
      - frontend # required to wait when the main job of running the specs is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}

  frontend:
    name: Frontend
    needs:
      - start-runner
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 11 ]

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: archivesspace
          MYSQL_USER: as
          MYSQL_PASSWORD: as123
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      solr:
        image: solr:9.4.1
        env:
          SOLR_MODULES: analysis-extras
        ports:
          - 8984:8983

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin

    - uses: './.github/actions/bootstrap'

    - name: Allow ArchivesSpace functions for app db user
      env:
        DB_PORT: "3307"
      run: |
        mysql --host 127.0.0.1 --port $DB_PORT -uroot -proot -e "SET GLOBAL log_bin_trust_function_creators = 1;"

    - name: Copy solr config from workspace to solr service
      env:
        SOLR_ID: ${{ job.services.solr.id }}
      run: |
        docker cp solr $SOLR_ID:/solr_conf_from_repo

    - name: Create ArchivesSpace Solr core
      env:
        SOLR_ID: ${{ job.services.solr.id }}
      run: |
        docker exec --tty $SOLR_ID solr create_core -p 8983 -c archivesspace -d /solr_conf_from_repo

    - name: Run Frontend tests
      run: |
        ./build/run frontend:selenium
        ./build/run frontend:test
      env:
        ARCHIVESSPACE_VERSION: ${{ github.ref }}

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: failed_spec_saved_pages(${{ matrix.java }})
        path: 'frontend/tmp/capybara'
