name: Indexer Testing

on:
  workflow_dispatch:
    inputs:
      java-version:
        description: Java version to run specs on
        required: true
        type: choice
        options:
          - '11'
          - '17'
        default: '11'

  workflow_call:
    inputs:
      java-version:
        description: Java version to run specs on
        required: true
        type: string
        default: '11'

  pull_request:
    paths:
      - '.github/workflows/indexer.yml'
      - 'indexer/**'

jobs:
  indexer:
    name: indexer_Java_v${{ inputs.java-version || 11 }} # https://archivesspace.atlassian.net/browse/ANW-2022
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version || 11 }}
        distribution: temurin

    - uses: './.github/actions/bootstrap'
      with:
        backend: true
        public: true
        indexer: true

    - name: Run Indexer tests
      env:
        ASPACE_TEST_BACKEND_URL: http://localhost:9999
      run: |
        ./build/run indexer:test
