name: Indexer Testing

on:
  pull_request:
    paths:
      - '.github/workflows/indexer.yml'
      - 'indexer/**'

jobs:
  indexer:
    name: indexer
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      matrix:
        java: [ 8, 11 ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin

    - uses: './.github/actions/bootstrap'

    - name: Run Indexer tests
      env:
        ASPACE_TEST_BACKEND_URL: http://localhost:9999
      run: |
        ./build/run indexer:test
